services:
  db:
    image: postgres:16-alpine
    container_name: showme_postgres
    restart: always
    environment:
      POSTGRES_DB: showme_db
      POSTGRES_USER: showme_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

secrets:
  db_password:
    file: ./db_password.txt