# Generated by Django 4.2.13 on 2024-06-26 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='saved_posts',
            field=models.ManyToManyField(blank=True, related_name='saved_by', to='home.post'),
        ),
    ]
