# Generated by Django 4.2.13 on 2024-07-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pic_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
