# Generated by Django 4.2.13 on 2024-06-18 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile_bio_profile_profile_picture_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='images/default_pic.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
