# Generated by Django 4.2.13 on 2024-07-07 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_profile_pic_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pic_color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
