# Generated by Django 4.2.13 on 2026-08-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='camera',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
