# Generated by Django 4.2.13 on 2026-08-10 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pic_color',
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('access_token', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('is_private', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('photographer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='home.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='home.gallery'),
        ),
    ]
