# Generated by Django 4.2.13 on 2026-08-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_post_pic_color_gallery_post_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='is_private',
        ),
        migrations.AddField(
            model_name='gallery',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
